import type { Metadata } from "next";

import "react-next-dates/dist/style.css";

export const metadata: Metadata = {
  title: "Votik",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>{children}</body>
    </html>
  );
}
