import { GoogleAnalytics } from "@next/third-parties/google";
import type { Metadata } from "next";
import Head from "next/head";

import "react-next-dates/dist/style.css";

export const metadata: Metadata = {
  title: "Votik",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <Head>
        <meta name="mobile-web-app-capable" content="yes" />
      </Head>
      <body>{children}</body>
      <GoogleAnalytics gaId="G-R1RJRTNCKF" />
    </html>
  );
}
