import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";

import "react-dates/lib/css/_datepicker.css";
import "rc-slider/assets/index.css";
// STYLE
import "../../styles/index.scss";
import "../../globals.css";
import "../../fonts/line-awesome-1.3.0/css/line-awesome.css";
import "react-dates/initialize";

import Footer from "@app/shared/Footer/Footer";
import { Tables } from "@app/types/database.types";
import { getSessionAndOrganizer } from "@app/lib/auth";
import NextTopLoader from "nextjs-toploader";

import { GoogleAnalytics } from "@next/third-parties/google";
import SiteHeader from "@app/organizers/components/SiteHeader/SiteHeader";

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  variable: "--font-bebas-neue",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Votik",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const organizerDetails: {
    organizer: Tables<"organizers"> | null;
  } = {
    organizer: null,
  };

  const { session, organizer } = await getSessionAndOrganizer();

  return (
    <html lang="en" className="dark">
      <body className={`${bebasNeue.variable}`}>
        <NextTopLoader
          showSpinner={false}
          color={"#c4fd07"}
          // color={"#430D7F"}
        />
        <div className="bg-white text-base dark:bg-neutral-900 text-neutral-900 dark:text-neutral-200">
          <SiteHeader session={session} organizer={organizer} />
          {children}
          <Footer />
        </div>
      </body>
      <GoogleAnalytics gaId="G-R1RJRTNCKF" />
    </html>
  );
}
